try:
	import glob
	import matplotlib.pyplot as plt
	import numpy as np
	import pandas as pd
	import scipy.stats as stats
	import seaborn as sns
except ImportError:
	print (".")



"""
-----------------------------------
Pseudorandom number generators (RNG)
-----------------------------------

While pseudorandom numbers are generated by a deterministic 
algorithm, we can mostly treat them as if they were true random
numbers and we will drop the "pseudo" prefix. Fundamentally, the 
algorithm generates random integers which are then normalized 
to give a floating print number 

Random numbers from other distributions are in turn generated
using these uniform random deviates.

"""


def rng(m = 2**32, a = 1103515, c= 12345):
	rng.current = (a * rng.current + c) % m
	return rng.current/m

