try:
	import glob
	import matplotlib.pyplot as plt
	import scipy.stats as stats
	import seaborn as sns
	import scipy.linalg as la
	import numpy as np
	import scipy.optimize as opt
	import matplotlib.pyplot as plt
	import pandas as pd
except ImportError:
	print (".")



"""
-----------------------------------
Pseudorandom number generators (RNG)
-----------------------------------

While pseudorandom numbers are generated by a deterministic 
algorithm, we can mostly treat them as if they were true random
numbers and we will drop the "pseudo" prefix. Fundamentally, the 
algorithm generates random integers which are then normalized 
to give a floating print number 

Random numbers from other distributions are in turn generated
using these uniform random deviates.

"""

def f(x):
	return x**3 - 3*x + 1

x = np.linspace(-3,3,100)
plt.axhline(0, c='red')
plt.plot(x, f(x));

from scipy.optimize import brentq, newton

bq1, bq2, bq3 = brentq(f, -3, 0), brentq(f, 0, 1), brentq(f, 1,3)

print(bq1, bq2, bq3)
